#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := neopixels
CPPFLAGS = "-Wno-unused-but-set-variable"
CPPFLAGS += "-Wno-unused-variable"

include $(IDF_PATH)/make/project.mk

